services:
  nodered:
    container_name: PathForensic-nodered
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=Europe/Stockholm
      - MQTT_BROKER_ADDRESS=mqtt
      - MQTT_BROKER_PORT=1883
      - MQTT_BROKER_USERNAME=
      - MQTT_BROKER_PASSWORD=
      - RECORDER_ADDRESS=IP or FQDN.  Leave blank if no recorder used.
      - MONGODB_ADDRESS=mongodb
      - MONGODB_PORT=27017
    ports:
      - '1888:1880'
    networks:
      - app_network
    volumes:
      - ./:/data
## Add comments below if you already have an MongoDB
  mongodb:
#    image: mongo:4.4.18  #Use this on RasPi  
    image: mongo:6.0.13  #Us this on PC
    container_name: PathForensic-mongodb
    restart: always
    environment:
      - MONGODB_AUTH=false
    networks:
      - app_network
    volumes:
      - ./mongodb:/data/db
## Add comments below if you already have an MQTT broker
  mqtt:
    container_name: PathForensic-MQTT
    restart: always
    image: eclipse-mosquitto
    user: '0'
    networks:
      - app_network
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto:/mosquitto/config
networks:
  app_network:
    driver: bridge
